### ISSUE TITLE
pmetalog and dmetalog gives fewer values than requested

### ISSUE THREAD

**Issue by tadamcz** [tjefferies/pymetalog#11]
I believe this happens when I give as input percentiles that are 'difficult' to fit, such as 
```
# a list of (p,x) tuples, where P(X<x)=p
percentiles = [(0.1,0) , (0.2,50) , (0.3,51)]
```
Files to reproduce are [here](https://github.com/tmkadamcz/distribution-converter/tree/9dc0ca2bd60944d553bd9c85bef206a08e30e336). Run [this file](https://github.com/tmkadamcz/distribution-converter/blob/9dc0ca2bd60944d553bd9c85bef206a08e30e336/pymetalog-reproducible-error.py)

**Comment by tjefferies** [comment]
So the issue with this one is the three term fit is not feasible for this set of quantile/data pairs. If you try to fit a 3 term metalog with these quantile/data values in the original .xlsx [file](http://www.metalogdistributions.com/metalogs.html) posted by Dr. Keelin (inventor of metalog), you'll receive an error. Notice how the 2 term metalog just barely passes through the (0.2, 50) and (0.3, 51) points. The error in fit typically happens when the data results in an S shaped CDF. ~~The package currently only allows for 3 term metalogs or greater and doesn't currently support 2 term metalogs.~~ Sorry misspoke on this one.

**Comment by isaacfab** [comment]
Often a metalog fit to data is not possible using the OLS method suggested by Dr. Keelin in his paper. We have developed a number of different methods that allow for best fit using different constrained optimization techniques. I maintain the R package and use a  linear program to do this best fit. For example here is the output of your example using R:

----
Parameters
 Term Limit:  3 
 Term Lower Bound:  2 
 Boundedness:  u 
 Bounds (only used based on boundedness):  0 60 
 Step Length for Distribution Summary:  0.001 
 Method Use for Fitting:  any 
 Number of Data Points Used:  3 
 Original Data Saved:  FALSE 
 
 Validation and Fit Method
 term valid         method
    2   yes Linear Program
    3   yes Linear Program
----

You can see that both the 2 and 3 term fit required the LP method so the OLS method did not return a valid metalog. @tjefferies did you have the LP fit in the current python deployment?

**Comment by tjefferies** [comment]
There was an issue with [a_vector.py](https://github.com/tjefferies/pymetalog/blob/master/pymetalog/a_vector.py#L165) where the `methodFit` variable wasn't being set when creating the metalog using `fit_method='LP'`. If you ran `pm.summary` on the fitted metalog after specifying `fit_method='LP'`, it would still print

```python
 term valid          method
    2   yes            OLS
    3   yes            OLS
```

instead of the expected output

```python
 term valid          method
    2   yes  Linear Program
    3   yes  Linear Program
```

See 7fed219f7db385b06928dc2eb382a9f1f5df2f11 for fix.

@isaacfab LP fit method is implemented and can be called using code below. Fit returns ok and program proceeds through the conditional checks on a Windows 10 machine, returning with no error. Tested using


numpy version: 1.18.2
pandas version: 1.0.3
scipy version: 1.4.1

@tmkadamcz What dependency versions are you using?

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pymetalog as pm
import scipy as sp


print('numpy version: {}'.format(np.__version__))
print('pandas version: {}'.format(pd.__version__))
print('scipy version: {}'.format(sp.__version__))

# a list of (p,x) tuples, where P(X<x)=p
percentiles = [(0.1,0),
		  (0.2,50),
		  (0.3,51)]

term = len(percentiles)

metalog_obj = pm.metalog(
		x = [tuple[1] for tuple in percentiles],
		probs =[tuple[0] for tuple in percentiles],
		boundedness = 'u',
		term_limit = term,
        fit_method = 'LP',
		step_len=0.01)

pm.summary(metalog_obj)

domain_for_debugging = [i for i in range(100)]
pdf_values = pm.dmetalog(metalog_obj,domain_for_debugging,term=term)
if len(pdf_values)!=len(domain_for_debugging):
    raise RuntimeError("dmetalog gave",len(pdf_values),"results, instead of",len(domain_for_debugging))

cdf_values = pm.pmetalog(metalog_obj,domain_for_debugging,term=term)
if len(cdf_values)!=len(domain_for_debugging):
    raise RuntimeError("pmetalog gave",len(cdf_values),"results, instead of",len(domain_for_debugging))
    
```

Plot of `cdf_values`

![Figure 2020-09-12 151052](https://user-images.githubusercontent.com/24706343/93004175-3a036300-f50a-11ea-8f04-f7eac17ff5f4.png)

There is a warning output during the fit, when using the LP method.

```
C:\..\pymetalog\pymetalog\a_vector.py:287: OptimizeWarning: The pivot operation produces a pivot value of: 8.0e-03, which is only slightly greater than the specified tolerance 1.0e-05. This may lead to issues regarding the numerical stability of the simplex method. Removing redundant constraints, changing the pivot strategy via Bland's rule or increasing the tolerance may help reduce the issue.
  lp_sol = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, method='simplex', options={"maxiter":5000, "tol":1.0e-5,"disp": False})
```

It may be worth it to move the `diff_error` parameter up to the initialization of the metalog class returned by `pm.metalog`. Currently `diff_error` is hardcoded to 0.001 during the main `a_vector_OLS_and_LP` [call](https://github.com/tjefferies/pymetalog/blob/master/pymetalog/metalog.py#L264). A seperate parameter for the `tol` parameter in the `linprog` call too.

```python
        self.output_dict = a_vector_OLS_and_LP(
            output_dict,
            bounds = self.bounds,
            boundedness = self.boundedness,
            term_limit = self.term_limit,
            term_lower_bound = self.term_lower_bound,
            fit_method = self.fit_method,
            alpha = self.alpha,
            diff_error = .001,
            diff_step = 0.001)
```
But that's kind of a separate issue. What's concerning about this is if I run 

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pymetalog as pm
import scipy as sp


print('numpy version: {}'.format(np.__version__))
print('pandas version: {}'.format(pd.__version__))
print('scipy version: {}'.format(sp.__version__))

# a list of (p,x) tuples, where P(X<x)=p
percentiles = [(0.1,0),
		  (0.2,50),
		  (0.3,51)]

term = len(percentiles)

metalog_obj = pm.metalog(
		x = [tuple[1] for tuple in percentiles],
		probs =[tuple[0] for tuple in percentiles],
		boundedness = 'u',
		term_limit = term,
        fit_method = 'any',
		step_len=0.01)

pm.summary(metalog_obj)

#  -----------------------------------------------
#  Summary of Metalog Distribution Object
#  -----------------------------------------------
 
# Parameters
#  Term Limit:  3 
#  Term Lower Bound:  2 
#  Boundedness:  u 
#  Bounds (only used based on boundedness):  [0, 1] 
#  Step Length for Distribution Summary:  0.01 
#  Method Use for Fitting:  OLS 
 

#  Validation and Fit Method Number of Data Points Used:  3 

#  term valid method
#     2   yes    OLS
#     3   yes    OLS

domain_for_debugging = [i for i in range(100)]
pdf_values = pm.dmetalog(metalog_obj,domain_for_debugging,term=term)
if len(pdf_values)!=len(domain_for_debugging):
    raise RuntimeError("dmetalog gave",len(pdf_values),"results, instead of",len(domain_for_debugging))

cdf_values = pm.pmetalog(metalog_obj,domain_for_debugging,term=term)
if len(cdf_values)!=len(domain_for_debugging):
    raise RuntimeError("pmetalog gave",len(cdf_values),"results, instead of",len(domain_for_debugging))
    
```

Or 

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pymetalog as pm
import scipy as sp


print('numpy version: {}'.format(np.__version__))
print('pandas version: {}'.format(pd.__version__))
print('scipy version: {}'.format(sp.__version__))

# a list of (p,x) tuples, where P(X<x)=p
percentiles = [(0.1,0),
		  (0.2,50),
		  (0.3,51)]

term = len(percentiles)

metalog_obj = pm.metalog(
		x = [tuple[1] for tuple in percentiles],
		probs =[tuple[0] for tuple in percentiles],
		boundedness = 'u',
		term_limit = term,
        fit_method = 'OLS',
		step_len=0.01)

pm.summary(metalog_obj)

#  -----------------------------------------------
#  Summary of Metalog Distribution Object
#  -----------------------------------------------
 
# Parameters
#  Term Limit:  3 
#  Term Lower Bound:  2 
#  Boundedness:  u 
#  Bounds (only used based on boundedness):  [0, 1] 
#  Step Length for Distribution Summary:  0.01 
#  Method Use for Fitting:  OLS 
 

#  Validation and Fit Method Number of Data Points Used:  3 

#  term valid method
#     2   yes    OLS
#     3   yes    OLS

domain_for_debugging = [i for i in range(100)]
pdf_values = pm.dmetalog(metalog_obj,domain_for_debugging,term=term)
if len(pdf_values)!=len(domain_for_debugging):
    raise RuntimeError("dmetalog gave",len(pdf_values),"results, instead of",len(domain_for_debugging))

cdf_values = pm.pmetalog(metalog_obj,domain_for_debugging,term=term)
if len(cdf_values)!=len(domain_for_debugging):
    raise RuntimeError("pmetalog gave",len(cdf_values),"results, instead of",len(domain_for_debugging))
    
```

The OLS fit returns ok, but the `RuntimeError("dmetalog gave",len(pdf_values),"results, instead of",len(domain_for_debugging))` gets raised. Running the program and commenting out the `dmetalog` call separately raises the RuntimeError after the `pmetalog` call too.

So now the questions are:
* Why is OLS failing in R package, failing in Excel, but returning ok in python? OLS for <img src="https://render.githubusercontent.com/render/math?math=\alpha"> coefficients given by

Math:

<img src="https://render.githubusercontent.com/render/math?math=\alpha = \left( Y^{T} Y %2B \lambda I \right)^{-1} Y^{T} \bar{z}">

Code:

```python
np.dot(np.dot(np.linalg.inv(np.dot(Y.T, Y) + alpha*eye), Y.T), z) # lambda -> alpha: default 0 reduces to OLS
```

* Why is OLS fit returning ok, but not providing expected output with class_method calls? Both class_method `dmetalog` and `pmetalog` calls make use of support `newtons_method_metalog` [function](https://github.com/tjefferies/pymetalog/blob/master/pymetalog/support.py#L289).
	* Changing `err = 1e-10` to lower tolerance `err = 1e-5` does not fix error
	* Changing `err = 1e-10` to lower tolerance `err = 1e-3` fixes error and returns values, but returns a uniform pdf/cdf (noise)
	
Need to move `err` [parameter](https://github.com/tjefferies/pymetalog/blob/master/pymetalog/support.py#L307) out to `newtons_method_metalog` [function](https://github.com/tjefferies/pymetalog/blob/master/pymetalog/support.py#L289) then out to class_method `dmetalog` [function](https://github.com/tjefferies/pymetalog/blob/master/pymetalog/class_method.py#L126) and class_method `pmetalog` [function](https://github.com/tjefferies/pymetalog/blob/master/pymetalog/class_method.py#L160).

Does upper bound of allowable range for `err = 1e-5` for `newtons_method_metalog` make the most sense?

**Comment by tadamcz** [comment]
I can confirm that when setting `fit_method = 'LP'`, I get the same results as you @tjefferies, using these dependencies:
```
numpy version: 1.19.2
pandas version: 1.1.2
scipy version: 1.5.2
```

However, it still states that the fit method is OLS in the summary:
```
 Validation and Fit Method
 term valid method
    2   yes    OLS
    3   yes    OLS
```

**Comment by tjefferies** [comment]
Rebuilt / Republished with fix to pypi under version 0.2.2. @tmkadamcz can you confirm the issue above has been fixed?

**Comment by tadamcz** [comment]
With pymetalog 0.2.2, and ` fit_method = 'any'`, I still get:

```
term valid method
    2   yes    OLS
    3   yes    OLS
...
RuntimeError: ('dmetalog gave', 0, 'results, instead of', 100)
```

https://gist.github.com/tmkadamcz/a8844f549fbe5b033496d89dc9720c17 

What's the expected output?

**Comment by tjefferies** [comment]
Haven’t forgotten about this... Been busy, but should have some time in coming weeks

**Comment by tadamcz** [comment]
I've got a fork now at https://github.com/tadamcz/pymetalog-tadamcz-fork. I've fixed a few bugs including the one we discussed above. There's a lot of work I could potentially do to refactor the package, but for now I'm just fixing bugs opportunistically when I encounter them. I'm using my fork to build this webapp: https://github.com/tadamcz/elicitor.
